### ISSUE TITLE
Can I download a html format of my preview?

### ISSUE THREAD

**Issue by jack1118** [honzababarik/vscode-api-blueprint-preview#5]
Can I download a html format of my preview?

**Comment by honzababarik** [comment]
Good idea, thank you! This is not yet possible but shouldn't be very hard to bring.

**Comment by jack1118** [comment]
Got it. Thank you. Expect to have the new feature.

**Comment by Alecsplus** [comment]
No news about his feature? I will find it very useful. Thanks.

**Comment by honzababarik** [comment]
Hi @Alecsplus, thank you for the push :-) I have just published version 0.9.3 where save as HTML feature is introduced. Please, let me know if it doesn't work as expected!

**Comment by Alecsplus** [comment]
Very good job, it works very well!
Thanks again.

**Comment by honzababarik** [comment]
Glad it helps @Alecsplus ! Closing issue.
